---
exclude_paths:
  - vendor/**/*
  - node_modules/**/*
  - db/migrate/**/*
  - bin/**/*
  - config/**/*
  - spec/**/*

detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    enabled: false
